/**
 * Created by liufeng on 2017/8/29.
 */
module.exports = {
  order_manage: '订单管理',
  order_list: '订单列表',
  goods_refunds: '商品退款申请',
  choose_goods: '取消商品申请',
  search: '搜索',
  choose: '请选择',
  choose1: '请选择尺码',
  search1: '普通搜索',
  search2: '高级搜索',
  Qty: 'Qty :',
  total: 'total:',
  order_number: 'order number',
  order_id: 'order Id',
  diff_refund: '差价退款',
  order_type: '红人订单',
  operation: '操作查询',
  change_goods: '换货',
  del_goods: '删除换货',
  order_operation: '查看',
  order_operation1: '订单标记',
  order_operation2: '退款/取消',
  order_operation3: '差价退款',
  order_operation4: '备注',
  order_operation5: '物流备注',
  order_operation6: '新增备注',
  order_operation7: '保存',
  order_operation8: '取消',
  order_operation9: '缺少备注',
  order_operation10: '缺少物流备注',
  allChoose: '全选',
  cancel: '取消',
  batchection: '批量部分发',
  guangzhou: '广州',
  west: '西部',
  platform: '平台订单取消',
  review: '批量审核',
  customerCancel: '客服取消',
  orderTrouble: '订单标记',
  orderTrouble1: '问题订单',
  orderTrouble2: '作废订单',
  orderTrouble3: '风控订单',
  orderTrouble4: '特殊订单',
  orderTrouble5: '紧急订单',
  TroubleCancel: '是否取消标记',
  refundBillStatus: '',
  refundBillStatus1: '已申请退款',
  refundBillStatus2: '退款中',
  refundBillStatus3: '已经退款',
  refundBillStatus4: '退款驳回',
  refundBillStatus5: '退款已取消',
  change1: '(被换)',
  change2: '换来的货',
  operationCheck: '操作人',
  operationCheck1: '时间',
  operationCheck2: '操作',
  checkSize: '查询尺码',
  submit: '提交',
  title: '标记为',
  title1: '备注',
  submitName: '保存',    // 提交name
  submitName1: '取消',
  submitName2: '取消标记',
  submitName3: '保留标记',
  submitName4: '换入sku',
  submitName5: '可换尺码',
  submitTitle: '缺少SKU',    // 提交提示
  submitTitle1: '缺少时间',
  submitTitle2: '确定删除换货吗？',
  submitTitle3: '缺少必填项',
  submitTitle4: '缺少标记',
  submitTitle5: '缺少备注',
  sagaTitle: '搜索失败: ',
  sagaTitle1: '高级搜索失败: ',
  sagaTitle2: '获取国家失败: ',
  sagaTitle3: '获取站点失败: ',
  sagaTitle4: '获取支付方式失败: ',
  sagaTitle5: '获取问题件类型失败: ',
  sagaTitle6: '获取会员等级失败: ',
  sagaTitle7: '获取订单状态失败: ',
  sagaTitle8: '获取取消类型失败: ',
  sagaTitle9: '获取商品状态失败: ',
  sagaTitle10: '获取商品操作查询失败: ',
  sagaTitle11: '获取备注失败: ',
  sagaTitle12: '添加备注失败: ',
  sagaTitle13: '添加备注成功',
  sagaTitle14: '获取物流备注失败: ',
  sagaTitle15: '添加物流备注失败: ',
  sagaTitle16: '添加物流备注成功',
  sagaTitle17: '获取商品尺码失败: ',
  sagaTitle18: '换货失败: ',
  sagaTitle19: '换货成功',
  sagaTitle20: '删除换货失败: ',
  sagaTitle21: '删除换货成功',
  sagaTitle22: '操作失败: ',
  sagaTitle23: '操作成功!',
  modifyDiffRefund: '修改退款详情',
  sagaTitle24: '必须勾选商品',
  sagaTitle25: '提交成功!',
  sagaTitle26: '提交失败:',
  sagaTitle27: '加入批量审核队列成功!',
  sagaTitle28: '加入部分发队列成功!',
  sagaTitle29: '操作成功', // 平台取消成功提示
  contentTitle: '暂无数据',
};
