/**
 * Created by liufeng on 2017/8/29.
 */
module.exports = {
  Integral_compensation: '补偿积分',
  order_manage: '订单管理',
  order_list: '订单列表',
  goods_refunds: '商品退款申请',
  choose_goods: '取消商品申请',
  search: '搜索',
  choose: '请选择',
  choose1: '请选择尺码',
  search1: '普通搜索',
  search2: '高级搜索',
  Qty: 'Quantity: ',
  total: 'total:',
  order_number: 'order number',
  order_id: 'order Id',
  diff_refund: '差价退款',
  order_type: '红人订单',
  operation: '操作查询',
  change_goods: '换货',
  del_goods: '删除换货',
  del_goods1: '删除换货',
  order_operation: '查看',
  order_operation1: '订单标记',
  order_operation2: '退款/取消',
  order_operation3: '差价退款',
  order_operation4: '备注',
  order_operation5: '物流备注',
  order_operation6: '新增备注',
  order_operation7: '保存',
  order_operation8: '取消',
  order_operation9: '缺少备注',
  order_operation10: '缺少物流备注',
  order_operation11: '全选商品',
  order_operation12: '批量无货审核',
  order_operation13: '批量无货',
  allChoose: '全选',
  cancel: '取消',
  batchection: '批量部分发',
  guangzhou: '广州',
  west: '西部',
  nansha: '南沙仓',
  america: '美国东部仓',
  europe: '欧洲仓',
  platform: '平台订单取消',
  review: '批量审核',
  customerCancel: '客服取消',
  customerCancel1: '客户取消',
  orderTrouble: '订单标记',
  orderTrouble1: '问题订单',
  orderTrouble2: '作废订单',
  orderTrouble3: '风控订单',
  orderTrouble4: '特殊订单',
  orderTrouble5: '紧急订单',
  orderTypeTitle1: '正常件',
  orderTypeTitle2: '问题件',
  orderTypeTitle3: '作废件',
  TroubleCancel: '是否取消标记',
  refundBillStatus: '',
  refundBillStatus1: '已申请退款',
  refundBillStatus2: '退款中',
  refundBillStatus3: '已经退款',
  refundBillStatus4: '退款驳回',
  refundBillStatus5: '退款已取消',
  change1: '(被换)',
  change2: '换来的货',
  operationCheck: '操作人',
  operationCheck1: '时间',
  operationCheck2: '操作',
  checkSize: '查询尺码',
  submit: '提交',
  title: '标记为',
  title1: '备注',
  submitName: '保存',    // 提交name
  submitName1: '取消',
  submitName2: '取消标记',
  submitName3: '保留标记',
  submitName4: '换入sku',
  submitName5: '可换尺码',
  submitTitle: '缺少SKU',    // 提交提示
  submitTitle1: '缺少时间',
  submitTitle2: '确定删除换货吗？',
  submitTitle3: '缺少必填项',
  submitTitle4: '缺少标记',
  submitTitle5: '缺少备注',
  sagaTitle: '搜索失败: ',
  sagaTitle1: '高级搜索失败: ',
  sagaTitle2: '获取国家失败: ',
  sagaTitle3: '获取站点失败: ',
  sagaTitle4: '获取支付方式失败: ',
  sagaTitle5: '获取问题件类型失败: ',
  sagaTitle6: '获取会员等级失败: ',
  sagaTitle7: '获取订单状态失败: ',
  sagaTitle8: '获取取消类型失败: ',
  sagaTitle9: '获取商品状态失败: ',
  sagaTitle10: '获取商品操作查询失败: ',
  sagaTitle11: '获取备注失败: ',
  sagaTitle12: '添加备注失败: ',
  sagaTitle13: '添加备注成功',
  sagaTitle14: '获取物流备注失败: ',
  sagaTitle15: '添加物流备注失败: ',
  sagaTitle16: '添加物流备注成功',
  sagaTitle17: '获取商品尺码失败: ',
  sagaTitle18: '换货失败: ',
  sagaTitle19: '换货成功',
  sagaTitle20: '删除换货失败: ',
  sagaTitle21: '删除换货成功',
  sagaTitle22: '操作失败: ',
  sagaTitle23: '操作成功!',
  modifyDiffRefund: '修改退款详情',
  sagaTitle24: '必须勾选商品',
  sagaTitle25: '提交成功!',
  sagaTitle26: '提交失败:',
  sagaTitle27: '加入批量审核队列成功!',
  sagaTitle28: '加入部分发队列成功!',
  sagaTitle29: '操作成功', // 平台取消成功提示
  sagaTitle30: '获取价格信息失败',
  sagaTitle31: '获取数据失败',
  sagaTitle32: '加入无货审核队列成功',
  sagaTitle33: '加入已审核队列成功',
  sagaTitle34: '库存下架同步成功',
  sagaTitle35: '库存下架同步失败,请去商城后台查看',
  contentTitle: '暂无数据',
  content_name: '退款原因',   // 内容名称
  content_name1: '备注信息',
  content_name2: '条记录',
  file_need_choose: '未选择任何文件',
  file_less_three: '最多3张',
  change_refund1: '退款编号: ',
  change_refund2: '退款状态: ',
  change_refund3: '退款原因: ',
  change_refund4: '退款类型: ',
  change_refund5: '驳回原因: ',
  refund_details1: 'PayPal',   // 退款详情
  refund_details2: 'masapay',
  refund_details3: 'worldpay',
  refund_details4: 'oceanpay',
  refund_details5: 'Paytm',
  refund_details6: 'PayU',
  refund_details7: 'yes bank',
  refund_details8: '其他',
  fetch_title1: '没有权限操作!',  // fetch
  fetch_title2: '服务器响应出错,请尝试 刷新 重试,或者联系开发人员需求帮助  _(:3 」∠)_',
  noGoods_name1: '仓库',
  noGoods_name2: '库存',
  noGoods_name3: '待占',
  noGoods_name4: '当前尺码下架',
  noGoods_name5: '全部尺码下架',
  noGoods_name6: '备货区',
  noGoods_name7: 'B区',
  noGoods_name8: 'C区东部',
  noGoods_name9: 'C区西部',
  noGoods_name10: 'D区',
  noGoods_name11: '广州仓',
  noGoods_name12: '广州欧洲仓',
  noGoods_name13: '广州美国仓',
  noGoods_name14: '无货下架',
  noGoods_name15: '库存清单',
  noGoods_name16: '下架站点',
  noGoods_name17: '确认无货',
  noGoods_name18: '返回已审核',
  noGoods_name19: 'B区待占：查询该sku+尺码，且 商品状态=已审核 或 备货中，的商品数之和',
  noGoods_name20: 'C区东部／西部待占：查询该sku+尺码， 商品状态=已审核 或 备货中，国家=美国，的商品数之和',
  noGoods_name21: 'D区待占：查询该sku+尺码，商品状态=已审核 或 备货中，国家=欧洲国家，的商品数之和',
  change_rl: '修改RL费用',
  not_RL: '未选择RL费用',
};
