module.exports = {
  basic: '基本信息',
  pay: '支付信息',
  refunds: '退款信息',
  return: '退货信息',
  order_log: '订单日志',
  shipping_address: 'Shipping Address',   // address
  billing_address: 'Billing Address',
  address_name: 'Name',
  address1: 'Address Line 1',
  address2: 'Address Line 2',
  address_city: 'City',
  address_country: 'Country',
  address_telephone: 'Telephone',
  address_company: 'Company Name',
  address_state: 'State/Province',
  address_post: 'Post/Zip Code',
  address_fax: 'Fax',
  address_type: 'Address Type',
  national_id: 'National Id',
  address_gender: 'Gender',
  address_first: 'First Name',
  address_last: 'Last Name',
  address_district: 'District',
  middle_name: 'Middle Name',
  address_father: 'Father Name',
  address_street: 'Street',
  address_national: 'National ID',
  address_english: 'English Name',
  address_passport: '护照号码',
  address_place: '签发地址',
  address_issue: '签发日期',
  address_cancel_stock: '取消库存占用',
  address_cancel_stock1: '是',
  address_cancel_stock2: '否',
  back_email: '退货邮箱',
  update_back_email: '更新退货邮箱',
  email_fail: '邮箱地址错误',
  update: '更新',
  edit: '编辑',
  save: '保存',
  confirm: '确定',
  cancel: '取消',
  cancel1: '重置',
  buy_date: '下单日期',
  pay_method: '支付方式',
  source_site: '来源站点',
  track_method: '运输方式',
  waist_time: '花费时间',
  pay_date: '付款日期',
  source_country: '来源国家',
  base_desc: '基本信息',
  goods_no_packge: '未形成包裹商品',
  packge: '包裹',
  return_goods: '退货商品',
  refund_goods: '退款商品',
  quality_control_done: '已品控',
  quality_control: '品控',
  examine_done: '已审核',
  back_goods_date: '回货日期',
  goods_status: '商品状态',
  image: '图片',
  sku: 'sku',
  code: '型号',
  price: '原价',
  sale_price: '销售价',
  discount_price: '折后价',
  send_goods_channel: '发货渠道',
  send_goods_number: '发货号',
  delivery_time: '发货时间',
  goods_rejected: '退货',
  goods_send_first: '优先发货',
  goods_send_first_cancel: '取消优先发货',
  part_send: '部分发',
  examine_order: '审核订单',
  Guangzhou: '广州',
  west: '西部',
  goods_rejected_record: '退货记录',
  payment_1: '支付渠道',   // 支付
  payment_2: '商品折后总价',
  payment_3: '钱包',
  payment_4: '优惠券码',
  payment_5: '优惠券抵扣金额',
  payment_6: 'COD服务费',
  payment_7: '付款凭证号',
  payment_8: '保险费',
  payment_9: '运费',
  payment_10: '积分',
  payment_11: '礼品卡抵扣',
  payment_12: '支付总价',
  payment_13: 'COD应付金额',
  payment_14: '交易记录',
  payment_15: '查看利润',
  payment_16: '商品总价',
  payment_17: '优惠券折扣',
  payment_18: '积分折扣',
  payment_19: 'VAT费用',
  payment_20: '关税费用',
  payment_21: '税费类型',  // 支付
  refund_1: '退款记录',   // 退款
  refund_2: '退款单编号',
  refund_3: '退款单类型',
  refund_4: '申请时间',
  refund_5: '申请人',
  refund_6: '申请金额',
  refund_7: '退款商品',
  refund_8: '退款路径',
  refund_9: '退款单状态',
  refund_10: '退款交易凭证号',
  refund_11: '驳回原因',
  refund_12: '操作',
  refund_13: '提现退款',
  refund_14: '修改申请',
  refund_15: '取消退款',
  refund_16: '确认取消此退款单', // 退款
  refund_17: '退款原因',
  refund_18: '银行代码',
  refund_19: '银行卡号',
  refund_20: '顾客姓名',
  refund_21: '发卡城市',
  refund_22: '账户信息',
  refund_23: '线下打款账户信息展示',
  refund_24: '订单号',
  refund_25: '账户',
  refund_account: '填写退款账户',
  order_return_1: '退货单号',   // 退货
  order_return_2: '退货单类型',
  order_return_3: '运单类型',
  order_return_4: '退货物流号',
  order_return_5: '退款状态',
  order_return_6: '退货单状态',
  order_return_7: '查看',
  order_return_8: '查看退货单',
  order_return_9: '上传退货物流号',
  order_return_10: '生成RL',
  order_return_11: '物流渠道',
  order_return_12: '运单号',
  order_return_13: '运单凭证',
  order_return_14: '上传',
  order_return_15: '缺少必填项',
  order_return_16: '删除',
  return_goods1: '批量选择退货原因',  // to-return-goods
  return_goods2: '退货商品',
  return_goods3: '退货原因',
  return_goods4: '退货数量',
  return_goods5: '照片',
  return_goods6: '上传图片',
  return_goods7: '退款路径',
  return_goods8: '退货运单类型',
  return_goods9: '退货商品入仓',
  return_goods10: '提交',
  return_goods11: '预计退款金额',
  return_goods12: '是否换货',
  return_goods13: '换货sku和尺码',
  submit_title: '缺少州省',
  submit_title1: '缺少城市',
  submit_title2: '缺少区',
  submit_title3: '缺少原因',
  submit_title4: '缺少照片',
  submit_title5: '缺少必填项',
  submit_title6: '换货sku和尺码是必填项',
  submit_title7: 'xxxx',
  submit_title8: 'xxxx',
  submit_info: '操作失败',
  submit_info1: '操作成功!',
  submit_info2: '获取数据失败',
  submit_info3: '加入部分发队列成功',
  submit_info4: '上传成功',
  submit_info5: '上传失败',
  submit_info6: '获取数据失败',
  submit_info7: '加入部分发队列成功',
  cash_content: '钱包可提现余额',  // 提现退款
  cash_content1: '不可提现金额',
  cash_content2: '退钱包总金额',
  cash_content3: '订单剩余可提现金额',
  cash_content4: '类型',
  cash_content5: '提现金额',
  cash_content6: '账户',
  cash_content7: '请输入正确的退款账户信息',
  cash_content8: '请输入正确的退款账户',
  cash_content9: '请输入币种',
  cash_content10: '请输入银行代码',
  cash_content11: '请输入银行卡号',
  cash_content12: '请输入顾客姓名',
  cash_content13: '请输入发卡城市',
  fankui: '物流问题反馈',
  fankuishow: '查看物流问题',
  rl_fee_required: 'rl费用必填',
  rl_deducted_costs: 'RL扣除费用',
  chaifen: '已拆分',
  yuanbaoguo: '原发货包裹号',
  return_link: '退货链接',
  return_copy: '一键复制',
  return_copy_title: '复制成功！',
  querenshouhuo: '确认收货',
  changeRL: '修改RL费用',
  confirm_received_error: '缺少运单号, 无法确认收货',
  上传的图片大小不能超过8M: '上传的图片大小不能超过8M',
  只可上传: '只可上传jpg、jpeg、png，单张图片不可超过8M',
  只可上传请确认: '只可上传jpg、jpeg、png，请确认！',
  prepared_goods: '已备货商品',
  shipping_warehouse: '发货仓',
};
