module.exports = {
  cancel_goods: '取消商品',
  need_cancel_goods: '需要退款商品',
  need_cancel_price: '需要退款金额',
  cancel_goods_reason: '取消商品原因',
  total_price: '实付金额',
  mark: '备注',
  freight_price: '运费和运费险',
  RL_price: 'RL 费用',
  giftcard: '礼品卡',
  wallet: '钱包',
  users: '用户',
  freight: '运费',
  insure: '运费险',
  point: '积分',
  coupon: '优惠券抵扣金额',
  can_be_refunded: '订单剩余可退金额',
  gift_refunded: '礼品卡可退金额',
  wallet_refunded: '钱包或用户可退金额',
  wait_refund: '待退款金额',
};
