module.exports = {
  cancel_goods: '取消商品',
  need_cancel_goods: '需要退款商品',
  need_cancel_price: '需要退款金额',
  cancel_goods_reason: '取消商品原因',
  total_price: '实付金额',
  mark: '备注',
  freight_price: '运费和运费险',
  RL_price: 'RL 费用',
  giftcard: '礼品卡',
  wallet: '钱包',
  users: '用户',
  freight: '运费',
  insure: '运费险',
  codFee: 'COD服务费',
  point: '积分',
  coupon: '优惠券抵扣金额',
  can_be_refunded: '订单剩余可退金额',
  gift_refunded: '礼品卡可退金额',
  wallet_refunded: '钱包可退金额',
  user_refunded: '用户可退金额',
  wait_refund: '待退款金额',
  no_over_price: '金额不可超过',
  no_back: '均退',
  no_no_back: '均不退',
  missing_something: '缺少必填项',
  get_goodsinfo_fail: '获取商品信息失败',
  get_backmoney_fail: '获取退款原因信息',
  submit_fail: '提交失败',
  please_select_a_refund_account: '请选择退款账户',
  Please_enter_a_user_refund_account: '请输入用户退款账户',
  Please_choose_pay_method: '请先选择退款路径',
  cancel_goods_title: '剩余商品应付金额低于$50;请确认是否取消',
  digits_are_needed: '10 digits are needed',
};
