/**
 * Created by fed on 2017/8/28.
 */
module.exports = {
  choose: '请选择',
  search_list: '订单列表',
  search1: '普通搜索',
  search2: '高级搜索',
  search3: '批量操作',
  order_number: '订单号',
  order_id: '订单ID',
  goods_id: '商品ID',
  email: '邮箱',
  shipping_no: '发货号',
  reference: '包裹号',
  telephone: '手机号',
  paytime: '付款时间',
  site: '站点',
  country: '国家',
  txn: '付款流水号',
  payment_method: '支付方式',
  trouble: '问题件类型',
  remark_user: '标记人',
  total_select: '美金金额',
  search: '搜索',
  tip: 'Tip',
  tip_title1: '搜索说明：',
  tip_title2: '1. 只可搜索一年内的订单；',
  tip_title3: '2. 付款时间最长可搜索一个月；',
  sku: 'sku',
  count: '有货件数>',
  member_level: '会员等级',
  order_status: '订单状态',
  goods_status: '商品状态',
  cancel_type: '取消类型',
  goods_time: '商品状态更新时间',
  time_interval_large: '时间间隔不能超过1个月',
  time_interval_large1: '结束时间必须大于开始时间',
};
