/**
 * Created by liufeng on 2017/8/29.
 */
module.exports = {
  order_manage: 'Order Admin',
  order_list: 'Order List',
  goods_refunds: '商品退款申请',
  choose_goods: '取消商品申请',
  search: '搜索en',
  choose: '请选择en',
  search1: 'General Search',
  search2: 'Advanced Search',
  Qty: 'Qty :',
  table: 'table :',
  order_number: 'Order No.',
  order_id: 'Order ID',
  diff_refund: 'Price Difference Refund',
  order_type: '红人订单',
  operation: '操作查询en',
  change_goods: '换货en',
  del_goods: '删除换货',
  order_operation: '查看en',
  order_operation1: '订单标记en',
  order_operation2: '退款/取消',
  order_operation3: '差价退款en',
  order_operation4: '备注',
  order_operation5: '物流备注',
  order_operation6: '新增备注',
  order_operation7: '保存',
  order_operation8: '取消',
  order_operation9: '缺少备注',
  order_operation10: '缺少物流备注en',
  allChoose: '全选en',
  cancel: '取消',
  guangzhou: '广州',
  west: '西部',
  platform: '平台订单取消',
  review: '批量审核',
  xxxx: '西部',
};
