/**
 * Created by liufeng on 2017/8/29.
 */
module.exports = {
  Integral_compensation: 'Points compensation',
  order_manage: 'Order Admin',
  order_list: 'Order List',
  goods_refunds: 'Item refund',
  choose_goods: 'Item Cancel',
  search: 'Search',
  choose: 'Please Select',
  choose1: 'Select Size',
  search1: 'General Search',
  search2: 'Advanced Search',
  Qty: 'Quantity: ',
  total: 'total:',
  order_number: 'Order No.',
  order_id: 'Order ID',
  diff_refund: 'Price Difference Refund',
  order_type: 'Guru Order',
  operation: 'Operation Records',
  change_goods: 'Exchange Item',
  del_goods: 'Exchanged Item Was Deleted',
  del_goods1: 'Delete Exchanged Item',
  order_operation: 'View Details',
  order_operation1: 'Mark the Order',
  order_operation2: 'Cancel/Refund',
  order_operation3: 'Price Difference Refund',
  order_operation4: 'Remark',
  order_operation5: 'Logistics Remark',
  order_operation6: 'Add New Remark',
  order_operation7: 'Save',
  order_operation8: 'Cancel',
  order_operation9: 'missing notes',
  order_operation10: 'Lack of shipping note',
  order_operation11: 'Select all',
  order_operation12: 'Out of stock confirmed in bulk',
  order_operation13: 'Mark as out of stock in bulk',
  allChoose: 'Select All',
  cancel: 'Cancel',
  batchection: 'Partial Shipped in Batch',
  guangzhou: 'Guangzhou warehouse',
  west: 'Western warehouse',
  nansha: 'nansha warehouse',
  america: 'Eastern United States warehouse',
  europe: 'Europe warehouse',
  platform: 'Platform Order cancelled',
  review: 'Bulk confirmation',
  customerCancel: 'Canceled by Customer Service',
  customerCancel1: 'Canceled by Customer',
  orderTrouble: 'Mark the Order',
  orderTrouble1: 'Problematic Order',
  orderTrouble2: 'Testing Order',
  orderTrouble3: 'Risk Order',
  orderTrouble4: 'Special Order',
  orderTrouble5: 'Rush Order',
  orderTypeTitle1: 'Regular Orders',
  orderTypeTitle2: 'Abnormal Orders',
  orderTypeTitle3: 'Invalid Orders',
  TroubleCancel: 'Are you sure you want to cancel the remark?',
  refundBillStatus: '',
  refundBillStatus1: 'Refund Applied',
  refundBillStatus2: 'Refunding',
  refundBillStatus3: 'Refunded',
  refundBillStatus4: 'Refund Rejected',
  refundBillStatus5: 'Refund Cancelled',
  change1: '(Been Exchanged)',
  change2: ' Exchanged',
  operationCheck: 'Operator',
  operationCheck1: 'Date',
  operationCheck2: 'Operation',
  checkSize: 'Look Up Size',
  submit: 'Submit',
  title: 'Remark',
  title1: 'Remark',
  submitName: 'Save',    // 提交name
  submitName1: 'Cancel',
  submitName2: 'Yes',
  submitName3: 'No',
  submitName4: 'SKU to Be Exchanged',
  submitName5: 'Size Available',
  submitTitle: 'missing SKU',    // 提交提示
  submitTitle1: 'missing time',
  submitTitle2: 'Are you sure to delete this exchanged item？',
  submitTitle3: 'missing mandatory field',
  submitTitle4: 'missing remarks',
  submitTitle5: 'missing notes',
  sagaTitle: 'Search Failed: ',
  sagaTitle1: 'Failed in advanced searching: ',
  sagaTitle2: 'Failed to acquire country info: ',
  sagaTitle3: 'Failded to acquire website info: ',
  sagaTitle4: 'Failed to acquire payment method: ',
  sagaTitle5: 'Failded to acquire problematic Order type: ',
  sagaTitle6: 'Failed to acquire member level: ',
  sagaTitle7: 'Failed to acquire order status: ',
  sagaTitle8: 'Failed to acquire cancelaction type: ',
  sagaTitle9: 'Failed to acquire item status: ',
  sagaTitle10: 'failed to acquire product search: ',
  sagaTitle11: 'Failed to acquire notes: ',
  sagaTitle12: 'Failed to add notes: ',
  sagaTitle13: 'Success in adding notes',
  sagaTitle14: 'Failed to acquire shipping note: ',
  sagaTitle15: 'Failed to add shipping note: ',
  sagaTitle16: 'Success in adding shipping note',
  sagaTitle17: 'Failed to acquire item size: ',
  sagaTitle18: 'Failed to exchange: ',
  sagaTitle19: 'Success in exchanging',
  sagaTitle20: 'Failed to delete exchange records: ',
  sagaTitle21: 'Success in deleting exchange records',
  sagaTitle22: 'Operation failed: ',
  sagaTitle23: 'Success in exchanging!',
  modifyDiffRefund: 'modify refund details',
  sagaTitle24: 'Check items required',
  sagaTitle25: 'Submitted successfully!',
  sagaTitle26: 'Submitted failed:',
  sagaTitle27: 'Success in adding multiple confimation lists!',
  sagaTitle28: 'Success in add partial confirmation lists!',
  sagaTitle29: 'Success in exchanging！', // 平台取消成功提示
  sagaTitle30: 'Failed to acquire price info',
  sagaTitle31: 'Failed to acquire datas',
  sagaTitle32: 'Join the "Out of stock confirmed"queue successfully',
  sagaTitle33: 'Join the "Order confirmed" queue successfully',
  sagaTitle34: '"Inventory off the shelf" sync succeeded',
  sagaTitle35: '"Inventory off the shelf" sync failed, please check the detail in Mywayec Platform',
  contentTitle: 'No data',
  content_name: 'Refund Reason',  // 内容名称
  content_name1: 'Notes',
  content_name2: 'Records in Total',
  file_need_choose: 'No files are selected',
  file_less_three: 'Maximum of 3 photos',
  change_refund1: 'Refund No.: ',
  change_refund2: 'Refund Status: ',
  change_refund3: 'Refund Reasons: ',
  change_refund4: 'Refund Type: ',
  change_refund5: 'Reject Reasons: ',
  refund_details1: 'PayPal',   // 退款详情
  refund_details2: 'masapay',
  refund_details3: 'worldpay',
  refund_details4: 'oceanpay',
  refund_details5: 'Paytm',
  refund_details6: 'PayU',
  refund_details7: 'yes bank',
  refund_details8: '其他',
  fetch_title1: 'No permission to operate!',  // fetch
  fetch_title2: 'The server responds with an error, try refreshing the retry, or contact the developer for help  _(:3 」∠)_',
  noGoods_name1: 'Warehouse',
  noGoods_name2: 'Inventory',
  noGoods_name3: 'Waiting on inventory',
  noGoods_name4: 'This size unlisted',
  noGoods_name5: 'All sizes unlisted',
  noGoods_name6: 'Stocking area',
  noGoods_name7: 'Warehouse B',
  noGoods_name8: 'east Warehouse C',
  noGoods_name9: 'west Warehouse C',
  noGoods_name10: 'Warehouse D',
  noGoods_name11: 'GZ Warehouse',
  noGoods_name12: 'GZ-EU Warehouse',
  noGoods_name13: 'GZ-US Warehouse',
  noGoods_name14: 'Unlisted',
  noGoods_name15: 'Inventory list',
  noGoods_name16: 'Unlisted from site',
  noGoods_name17: 'Out of stock confirmed',
  noGoods_name18: 'Back to confirmed',
  noGoods_name19: 'Warehouse B - assigned sku+size, item status = confirmed or items in processing',
  noGoods_name20: 'Eastern/Western warehouse C - assigned sku+size, item status = confirmed or items in processing, country = United States',
  noGoods_name21: 'Warehouse C - assigned sku+size, item status = comfirmed or items in processing, country=European countries',
};
