/**
 * Created by shenjialin on 2017/11/24.
 */
module.exports = {
  billno: '订单号',
  package_no: '包裹号',
  user_name: '处理人',
  status: '状态',
  site_from: '站点来源',
  ship_method: '渠道',
  type: '类型',
  payment_method: '是否COD',
  is_delete: '删除标记',
  commitTime: '提交时间',
  search: '搜索',
  piliangdelete: '批量删除',
  piliangrecheck: '批量重新校验',
  piliangdaochu: '批量导出',
  reason: '失败原因',
  country_name: '国家',
  commit_user: '提交人',
  add_time: '提交时间',
  last_update_time: '处理时间',
  operation: '操作',
  editAddr: '编辑地址',
  recheck: '重新校验',
  delete: '删除',
  audited: '已审核',
  processed: '已处理',
  text1: '请先选择',
  text2: '确定要删除该选择项？',
  text3: '是',
  text4: '否',
  text5: '确定要重新校验该选择项？',
  text6: '确定要导出该选择项？',
  text7: '确定要审核该选择项？',
  text8: '确定要处理该选择项？',
  country: '国家',
  BatchReviewed: '批量已审核',
  BatchProcessed: '批量已处理',
};
