const prefix = 'platform-order-management-';
export const getListPlatForm = `${prefix}getListPlatForm`;
export const change = `${prefix}change`;
export const getListLogisticChannel = `${prefix}getListLogisticChannel`;
export const changePage = `${prefix}changePage`;
export const add = `${prefix}add`;
export const edit = `${prefix}edit`;
export const addLogisticChannel = `${prefix}addLogisticChannel`;
export const fetchEditDataSuccess = `${prefix}fetchEditDataSuccess`;
