module.exports = {
  order_amount: 'Total Amount',
  refund_amount: 'Refund Amount',
  gift_card: 'Gift Card',
  wallet: 'Wallet',
  client: 'Account',
  overflow: 'Overpayment Refund',
  placeholder: 'Please input the refund account of customer',
  refundreason: 'Refund Reasons',
  remark: 'Note',
  commit: 'Submit',
  cancel: 'Cancel',
  amount_paid: 'Amount Paid',
  worldpay: 'worldpay',
  carriage: 'Shipping',
  carriage_Insurance: 'Insurance',
  integrate: 'Points',
  Coupon_Discount: 'Coupon Deducted Amount',
  order_amount_refundable: 'Order Refundable  Amount',
  gift_card_refundable: 'Gift Card Refundable Amount',
  clientandwallet_refundable: 'Wallet/Account Refundable Amount',
  waiting_amount: 'Amount Need to Be Refunded',
  need_refund_goods: 'Items Need a Refund',
  adjustment_refund: 'Price Difference Refund',
  reason_list_failed: 'Failed to acquire lists of refund reasons',
  refund_priceinfo_failed: 'Failed to acquire lists of refund info',
  submit_fail: 'Submit Failed',
  under50: 'Amount paypable of the remaining items is less than $50: Please confirm cancel or not',
};

