module.exports = {
  order_amount: '订单金额en',
  refund_amount: '退款金额en',
  gift_card: '礼品卡en',
  wallet: '钱包en',
  client: '客户en',
  overflow: '溢出线下打款en',
  placeholder: '请输入用户退款账户en',
  refundreason: '退款原因en',
  remark: '备注en',
  commit: '提交en',
  cancel: '取消en',
  amount_paid: '实付金额en',
  worldpay: 'worldpay',
  carriage: '运费en',
  carriage_Insurance: '运费险en',
  integrate: '积分en',
  Coupon_Discount: '优惠券抵扣金额en',
  order_amount_refundable: '订单剩余可退金额en',
  gift_card_refundable: '礼品卡可退金额en',
  clientandwallet_refundable: '用户和钱包可退金额en',
  waiting_amount: '待退金额en',
  need_refund_goods: '需要退款商品en',
  adjustment_refund: '差价退款en',
  reason_list_failed: '获取退款原因列表失败en',
  refund_priceinfo_failed: '获取退款信息列表失败en',
  submit_fail: '提交失败',
};
