module.exports = {
  order_amount: 'Total Amount',
  refund_amount: 'Refund Amount',
  gift_card: 'Gift Card',
  wallet: 'Wallet',
  client: 'Account',
  overflow: 'Overpayment Refund',
  placeholder: '请输入用户退款账户',
  refundreason: 'Refund Reasons',
  remark: 'Note',
  commit: 'Submit',
  cancel: 'Cancel',
  amount_paid: 'Amount Paid',
  worldpay: 'worldpay',
  carriage: 'Shipping',
  carriage_Insurance: 'Insurance',
  integrate: 'Points',
  Coupon_Discount: 'Coupon Deducted Amount',
  order_amount_refundable: 'Order Refundable  Amount',
  gift_card_refundable: 'Gift Card Refundable Amount',
  clientandwallet_refundable: 'Wallet/Account Refundable Amount',
  waiting_amount: 'Amount Need to Be Refunded',
  need_refund_goods: 'Items Need a Refund',
  adjustment_refund: 'Price Difference Refund',
  reason_list_failed: '获取退款原因列表失败',
  refund_priceinfo_failed: '获取退款信息列表失败',
  submit_fail: 'Submit Failed',
};

