module.exports = {
  basic: 'Basic Info',
  pay: 'Payment Info',
  refunds: 'Refund Info',
  return: 'Return Info',
  order_log: 'Order Record',
  shipping_address: 'Shipping Address',   // address
  billing_address: 'Billing Address',
  address_name: 'Name',
  address1: 'Address Line 1',
  address2: 'Address Line 2',
  address_city: 'City',
  address_country: 'Country',
  address_telephone: 'Telephone',
  address_company: 'Company Name',
  address_state: 'State/Province',
  address_post: 'Post/Zip Code',
  address_fax: 'Fax',
  address_gender: 'Gender',
  address_first: 'First Name',
  address_last: 'Last Name',
  address_district: 'District',
  address_father: 'Father Name',
  address_street: 'Street',
  address_national: 'National ID',
  back_email: 'Return Email',
  update_back_email: 'Update Return Email',
  email_fail: '邮箱地址错误',
  update: 'update',
  edit: 'Edit',
  save: 'Save',
  confirm: 'Confirm',
  cancel: 'Cancel',
  cancel1: 'Reset',
  buy_date: 'Order Time',
  pay_method: 'Payment Method',
  source_site: 'Original Site',
  track_method: 'Shipping Method',
  waist_time: 'Time-Taken',
  pay_date: 'Payment Time',
  source_country: 'Original Country',
  base_desc: 'Basic Info',
  goods_no_packge: 'Item in Processing',
  packge: 'Package',
  return_goods: 'Item Returned',
  refund_goods: 'Item Refunded',
  quality_control_done: 'Item Been Assessed',
  quality_control: 'Item Assessment',
  examine_done: 'Order Confirmed',
  back_goods_date: 'Date of Restocking',
  goods_status: 'Item Status',
  image: 'Picture',
  sku: 'sku',
  code: 'Size',
  sale_price: 'Retail Price',
  discount_price: 'Discount Price',
  send_goods_channel: '发货渠道',
  send_goods_number: 'Shipping No.',
  goods_rejected: 'Return the Item',
  goods_send_first: 'Priority Delivery',
  goods_send_first_cancel: '取消优先发货',
  part_send: 'Partial Shipped',
  examine_order: '审核订单',
  Guangzhou: '广州',
  west: '西部',
  goods_rejected_record: 'Return Record',
  payment_1: 'Payment Method',   // 支付
  payment_2: '商品折后总价',
  payment_3: 'Wallet',
  payment_4: 'Discount Code',
  payment_5: '抵扣显示金额',
  payment_6: 'COD Service Charge',
  payment_7: 'Payment Transacton ID',
  payment_8: 'Shipping Insurance',
  payment_9: 'Shipping Fee',
  payment_10: 'Points',
  payment_11: 'Gift Card',
  payment_12: 'Payment Total',
  payment_13: 'Amount To Be Paid (COD)',
  payment_14: 'Payment Record',
  payment_15: 'View Profit',
  payment_16: '商品总价',
  payment_17: 'Discount Price',
  payment_18: 'Points',
  payment_19: 'xxxx',
  payment_20: 'xxxx',
  payment_21: 'xxxx',  // 支付
  refund_1: 'Refund Record',   // 退款
  refund_2: 'Refund No.',
  refund_3: 'Refund Type',
  refund_4: 'Application Date',
  refund_5: 'Applicant',
  refund_6: 'Refund Amount', //  申请金额
  refund_7: 'Refund Item', // 退款商品
  refund_8: 'Refund Path',
  refund_9: 'Refund Status',
  refund_10: 'Refund Transaction ID',
  refund_11: 'Reject Reasons',
  refund_12: 'Operation',
  refund_13: 'Refund Withdraw',
  refund_14: '修改申请',
  refund_15: '取消退款',
  refund_16: '确认取消此退款单', // 退款
  order_return_1: 'RAN',   // 退货
  order_return_2: 'Return Applied Type',
  order_return_3: 'Waybill Type',
  order_return_4: 'Return Tracking No.',
  order_return_5: 'Refund Status',
  order_return_6: 'Returned  Status',
  order_return_7: 'View Details',
  order_return_8: 'View Return Label',
  order_return_9: 'Upload Return info',
  order_return_10: '生成RL',
  order_return_11: 'Shipping Channel',
  order_return_12: 'Return Shipping No.',
  order_return_13: 'Return Shipping Receipt',
  order_return_14: 'Upload ',
  order_return_15: '缺少必填项',
  order_return_16: 'Delete',
  return_goods1: 'Select Return Reasons In  Bulk',  // to-return-goods
  return_goods2: 'Item',
  return_goods3: 'Reasons',
  return_goods4: 'Quantities',
  return_goods5: 'Images',
  return_goods6: 'Upload Image',
  return_goods7: 'Refund Path',
  return_goods8: 'Return Request Type',
  return_goods9: 'Return Warehouses',
  return_goods10: 'Submit',
  submit_title: '缺少州省',
  submit_title1: '缺少城市',
  submit_title2: '缺少区',
  submit_title3: '缺少原因',
  submit_title4: '缺少照片',
  submit_title5: '缺少必填项',
  submit_title6: 'xxxx',
  submit_info: '操作失败',
  submit_info1: '操作成功!',
  submit_info2: '获取数据失败',
  submit_info3: '加入部分发队列成功',
  submit_info4: '上传成功',
  submit_info5: '上传失败',
  submit_info6: '获取数据失败',
  submit_info7: '加入部分发队列成功',
  cash_content: '钱包可提现余额',  // 提现退款
  cash_content1: '不可提现金额',
  cash_content2: '退钱包总金额',
  cash_content3: '订单剩余可提现金额',
  cash_content4: 'Type',
  cash_content5: 'Withdraw Amount',
  cash_content6: '账户',
  cash_content7: '请输入正确的退款账户信息',
  cash_content8: '请输入正确的退款账户',
};
