module.exports = {
  cancel_goods: '取消商品en',
  need_cancel_goods: '需要退款商品en',
  need_cancel_price: '需要退款金额en',
  cancel_goods_reason: '取消商品原因en',
  total_price: '实付金额en',
  mark: '备注en',
  freight_price: '运费和运费险en',
  RL_price: 'RL 费用en',
  giftcard: '礼品卡en',
  wallet: '钱包en',
  users: '用户en',
  freight: '运费en',
  insure: '运费险en',
  point: '积分en',
  coupon: '优惠券抵扣金额en',
  can_be_refunded: '订单剩余可退金额en',
  gift_refunded: '礼品卡可退金额en',
  wallet_refunded: '钱包或用户可退金额en',
  wait_refund: '待退款金额en',
  no_over_price: '金额不可超过en',
  no_back: '均退en',
  no_no_back: '均不退en',
  missing_something: '缺少必填项en',
  get_goodsinfo_fail: '获取商品信息失败en',
  get_backmoney_fail: '获取退款原因信息en',
  submit_fail: '提交失败en',
  please_select_a_refund_account: '请选择退款账户',
  Please_enter_a_user_refund_account: '请输入用户退款账户',
};
