module.exports = {
  cancel_goods: 'Cancel Items',
  need_cancel_goods: '需要退款商品',
  need_cancel_price: 'Refund Amount',
  cancel_goods_reason: 'Cancel Reasons',
  total_price: 'Amount Paid',
  mark: 'Note',
  freight_price: 'Shipping Price and Insurance Price',
  RL_price: 'Return Label Fee',
  giftcard: 'Gift Card',
  wallet: 'Wallet',
  users: 'Account',
  freight: 'Shipping Fee',
  insure: 'Shipping Insurance',
  point: 'Ponits',
  coupon: 'Coupon Deducted Amount',
  can_be_refunded: 'Order Refundable  Amount',
  gift_refunded: 'Gift Card Refundable Amount',
  wallet_refunded: 'Wallet Refundable Amount',
  user_refunded: 'Account Refundable Amount',
  wait_refund: 'Amount Need to Be Refunded',
  no_over_price: '金额不可超过',
  no_back: 'All Needs to Be Refunded',
  no_no_back: 'No Refund',
  missing_something: '缺少必填项',
  get_goodsinfo_fail: '获取商品信息失败',
  get_backmoney_fail: '获取退款原因信息',
  submit_fail: 'Submit Failed',
  please_select_a_refund_account: '请选择退款账户',
  Please_enter_a_user_refund_account: '请输入用户退款账户',
};
