module.exports = {
  channel_title: '渠道说明:',
  channel_title1: 'TKs Feedback: 客户通过提交Tickets向客服反馈的问题',
  channel_title2: 'Payment Platform : 客户在PayPal WP平台反馈的问题',
  channel_title3: 'Advertising Platform: 客户在国外第三方评价平台(如: trustpilot)反馈的问题',
  channel_title4: 'Product Reviews: 客户直接在网站上产品页的产品评论',
  channel_title5: 'QC Feedback: 仓库质检人员在退货入仓时检查反馈的问题',
  channel_title6: 'Other Website Feedback: 亚马逊、速卖通等平台上订单，用户反馈的问题',
  channel_title7: '退货中心: 客户主动申请退货后, 自动生成的品控问题',
  channel_title8: 'Blogger/Celebrity Review: 作为红人营销推广的商品, 收到的反馈问题',
  order_number: 'Order NO.',
  control_goods: 'Assessment Items',
  control_channel: 'Feedback Origins',
  control_type: 'Assessment Type',
  control_img: 'Images(2 Images limited)',
  control_title: '(只可上传jpg、jpeg、png，单张图片不可超过3M)',
  submitName: '保存',    // 提交name
  submitName1: 'Cancel',
  submitName2: 'xxxx',
  submitName3: 'Submit',
  submitName4: 'Reset',
  submitTitle: '上传图片尺寸上限3M',    // 提交提示
  submitTitle1: '请上传正确的图片格式',
  submitTitle2: '上传成功。',
  submitTitle3: '上传失败。',
};
