module.exports = {
  cancel_goods: 'Cancel Items',
  need_cancel_goods: 'Items required to refund',
  need_cancel_price: 'Refund Amount',
  cancel_goods_reason: 'Cancel Reasons',
  total_price: 'Amount Paid',
  mark: 'Note',
  freight_price: 'Shipping Price and Insurance Price',
  RL_price: 'Return Label Fee',
  giftcard: 'Gift Card',
  wallet: 'Wallet',
  users: 'Account',
  freight: 'Shipping Fee',
  insure: 'Shipping Insurance',
  codFee: 'COD Service Charge',
  point: 'Ponits',
  coupon: 'Coupon Deducted Amount',
  can_be_refunded: 'Order Refundable  Amount',
  gift_refunded: 'Gift Card Refundable Amount',
  wallet_refunded: 'Wallet Refundable Amount',
  user_refunded: 'Account Refundable Amount',
  wait_refund: 'Amount Need to Be Refunded',
  no_over_price: 'Amount not allow to exceed',
  no_back: 'All Needs to Be Refunded',
  no_no_back: 'No Refund',
  missing_something: 'missing mandatory field',
  get_goodsinfo_fail: 'Failed to acquire item details',
  get_backmoney_fail: 'Failed to acquire refund reasons',
  submit_fail: 'Submit Failed',
  please_select_a_refund_account: 'Please select refund account',
  Please_enter_a_user_refund_account: 'Please input the refund account of customer',
  Please_choose_pay_method: 'Please select refund method',
  cancel_goods_title: 'Amount paypable of the remaining items is less than $50: Please confirm cancel or not',
};
