/**
 * Created by fed on 2017/8/28.
 */
module.exports = {
  choose: 'Please Select',
  search_list: '自定义列表',
  search1: 'General Search',
  search2: 'Advanced Search',
  search3: '批量操作',
  order_number: 'order number',
  order_id: 'order Id',
  email: 'email',
  shipping_no: 'Shipping No.',
  reference: 'Parcel No.',
  telephone: 'Phone number',
  paytime: 'Payment Time',
  site: 'Site',
  country: 'Country',
  txn: 'Payment Transacton ID',
  payment_method: 'Payment Method',
  trouble: 'Problematic Order Type',
  remark_user: '标记人',
  total_select: 'Total Amount (US$ )',
  search: 'Search',
  tip: 'Tip',
  tip_title: '搜索说明：\n 1. 只可搜索一年内的订单；\n 2. 付款时间最长可搜索一个月；',
  sku: 'sku',
  count: 'Quantity of Item in Stock >',
  member_level: '会员等级',
  order_status: '订单状态',
  goods_status: '商品状态',
  cancel_type: '取消类型',
  goods_time: 'Update Time of Item Status',
  time_interval_large: '时间间隔不能超过30天en',
};
