/**
 * Created by shenjialin on 2017/11/24.
 */
module.exports = {
  billno: 'OrderNumber',
  package_no: 'ParcelNo.',
  user_name: 'UserName',
  status: 'Status',
  site_from: 'Site',
  ship_method: 'Channels',
  type: 'Type',
  payment_method: 'PayMethod',
  is_delete: 'IsDelete',
  commitTime: 'SubmitTime',
  search: 'Search',
  piliangdelete: 'BatchDeletion',
  piliangrecheck: 'BatchRecheck',
  piliangdaochu: 'BatchExport',
  reason: 'FailReason',
  country_name: 'Country',
  commit_user: 'Submitter',
  add_time: 'AddTime',
  last_update_time: 'LastTime',
  operation: 'Operation',
  editAddr: 'EditAddr',
  recheck: 'Recheck',
  delete: 'Delete',
  audited: 'Audited',
  processed: 'Processed',
  text1: 'Please select first',
  text2: 'Are you sure delete this task?',
  text3: 'YES',
  text4: 'NO',
  text5: 'Are you sure recheck this task?',
  text6: 'Are you sure export this task?',
  text7: 'Are you sure audit this task?',
  text8: 'Are you sure process this task?',
  country: 'country',
  BatchReviewed: 'BatchReviewed',
  BatchProcessed: 'BatchProcessed',
};
