module.exports = {
  被换商品: '被换商品',
  换货商品: '换货商品',
  自定义SKU: '自定义SKU',
  尺码: '尺码',
  确定: '确定',
  没选尺码: '没选尺码',
  提交: '提交',
  没有换货信息: '没有换货信息',
  信息不全: '信息不全',
  删除: 'Delete',
  exchangeReason: 'exchange reason',
  paymentOrder: 'payment order no.',
  paymentAccount: 'payment account',
  paymentBill: 'payment currency',
  paymentAmount: 'payment amount',
  noReason: 'you must select a reason',
  cancel: 'cancel',
};
