module.exports = {
  被换商品: 'changed goods',
  换货商品: 'Exchange goods',
  自定义SKU: 'customize SKU',
  尺码: 'size',
  确定: 'confirm',
  没选尺码: 'no size',
  提交: 'submit',
  没有换货信息: 'no changed information',
  信息不全: '信息不全',
  删除: 'Incomplete information',
  exchangeReason: 'exchange reason',
  paymentOrder: 'payment order no.',
  paymentAccount: 'payment account',
  paymentBill: 'payment currency',
  paymentAmount: 'payment amount',
  noReason: 'you must select a reason',
  cancel: 'cancel',
};
