/**
 * Created by liufeng on 2017/11/14.
 */
module.exports = {
  search_list: '退货列表',
  refund_number: '退货单号',
  order_number: '订单号',
  email: '用户邮箱',
  tracking_no: '运单号',
  good_sn: '商品sku',
  site: '站点',
  country: '国家',
  insurance: '退货险',
  warehouse: '入库仓库',
  returns_status: '退货单状态',
  trouble: '问题件',
  shipping_status: '包裹状态',
  refund_status: '退款状态',
  is_cod: '是否COD',
  member_level: '会员等级',
  return_label_type: '运单类型',
  order_type: '退货单类型',
  search_title: '请选择',
  search: '搜索',
  export: '导出EXL',
  batch_update: '批量更新运单号',
  tracking_update: '更新运单号',
  update: '点击上传',
  download: '下载地址',
  logistics: '物流渠道',
  tracking: '运单号',
  shipping_time: '包裹更新时间',
  last_time: '操作时间',
  refund_time: '退款时间',
  operate1: '查看详情',
  submit: '提交',
  cancel: '取消',
  operationCheck: '操作人',
  operationCheck1: '时间',
  operationCheck2: '操作',
  submitName: '保存',    // 提交name
  submitName1: '取消',
  submitName2: '全部',
  submitName3: '待退款',
  submitName4: '驳回',
  submitTitle: '结束时间必须大于开始时间', // 提交提示
  submitTitle1: '获取数据失败: ',
  submitTitle2: '搜索失败: ',
  submitTitle3: '导出失败: ',
  submitTitle4: '导出成功！',
  content: '退金额($)',
  申请退货时间: '申请退货时间',
  退货拆包时间: '退货拆包时间',
  办结时间: '办结时间',
  上传的图片大小不能超过8M: '上传的图片大小不能超过8M',
};
