/**
 * Created by liufeng on 2017/9/19.
 */
module.exports = {
  search_list: '退款列表',
  refund_number: '退款编号',
  order_number: '订单号',
  email: '用户邮箱',
  applicant: '申请人',
  operator: '操作人',
  refund_type: '退款类型',
  refund_path: '退款路径',
  path_status: '退款记录状态',
  site: '站点',
  apply_time: '退款申请日期',
  country: '国家',
  member_level: '会员等级',
  bill_status: '退款单状态',
  refund_time: '退款日期',
  search: '搜索',
  operate: '操作',
  operate1: '查看详情',
  choose: '请选择 xxxxx',
  choose1: '请选择尺码',
  Qty: 'Qty :',
  total: 'total:',
  order_id: 'order Id',
  diff_refund: '差价退款',
  order_type: '红人订单',
  operation: '操作查询',
  change_goods: '换货',
  del_goods: '删除换货',
  order_operation: '查看',
  order_operation1: '订单标记',
  order_operation2: '退款/取消',
  order_operation3: '差价退款',
  order_operation4: '备注',
  order_operation5: '物流备注',
  order_operation6: '新增备注',
  order_operation7: '保存',
  order_operation8: '取消',
  order_operation9: '缺少备注',
  order_operation10: '缺少物流备注',
  submit: '提交',
  cancel: '取消',
  operationCheck: '操作人',
  operationCheck1: '时间',
  operationCheck2: '操作',
  submitName: '保存',    // 提交name
  submitName1: '取消',
  submitTitle: '结束时间必须大于开始时间', // 提交提示
};
