module.exports = {
  submit: '确认',
  base_refund_code: '退款编号',
  base_order_number: 'Order NO.',
  base_order_total: '订单总金额',
  base_gift_card: 'Gift Card',
  base_pay_method: '支付方式',
  base_pay_number: '支付交易号',
  base_refund_need: '剩余可退金额',
  base_user: '用户',
  base_insuer: '运费和运费险',
  base_rl_fee: 'RL扣除费用',
  base_wait_refund: '待退款金额',
  base_refund_type: '退款类型',
  base_refund_reson: '退款原因',
  base_register_time: '申请时间',
  base_register_user: '申请人',
  base_refund_status: '退款单状态',
  base_refund_remark: '查看备注信息',
  base_add_remark: '新增备注',
  base_reject: '驳回',
  base_pass: '通过',
  base_refund_path: 'Refund Path',
  base_wallet_total: '用户钱包总额',
  base_need_price: 'Withdraw Amount',
  base_need_user: '退款提交人',
  base_need_operate: '退款操作人',
  base_refund_need_operate: '退款返还金额',
  base_refund_price: '退款金额',
  goods_need_refund: '需要退款的商品信息',
  goods_code: '编号',
  goods_refund: '退款商品',
  goods_sale: '销售价',
  goods_buy: '折后价',
  info_refund_info: 'Refund info',
  info_account: '账户',
  info_account_info: '账户信息',
  info_refund_protocal: '退款交易凭证号',
  info_refund_status: '退款状态',
  info_operate_time: '退款时间',
  info_renfund: '退款',
  info_renfund_agian: '重新退款',
  logs_renfund_logs: '退款操作日志',
  logs_logs: '操作日志',
  no_fifty: '不可超过50个字符',
  no_twohundernd: '不可超过200个字符',
  modals_rejec_reason: '驳回理由',
  modals_rejec_reason_tip: '请填写驳回理由，必填',
  modals_submit_refund: '确认退款',
  modals_refund_protocal: '交易凭证号',
  modals_refund_protocal_number: '退款交易号',
  modals_tip_offline: '线下退款请填写此信息',
  modals_tip_need: '请填写退款交易凭证号',
};
