module.exports = {
  被换商品: '被换商品',
  换货商品: '换货商品',
  自定义SKU: '自定义SKU',
  尺码: '尺码',
  确定: '确定',
  没选尺码: '没选尺码',
  提交: '提交',
  没有换货信息: '没有换货信息',
  信息不全: '信息不全',
  删除: '删除',
  exchangeReason: '换货原因',
  paymentOrder: '打款交易凭证号',
  paymentAccount: '打款账户',
  paymentBill: '打款币种',
  paymentAmount: '打款金额',
};
